name = "Loess"
uuid = "4345ca2d-374a-55d4-8d30-97f9976e7612"
version = "0.6.5"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distances = "0.7, 0.8, 0.9, 0.10"
LinearAlgebra = "1"
Statistics = "1"
StatsAPI = "1.1"
StatsFuns = "1"
julia = "1.8"

[extras]
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "RDatasets", "Test"]
